# Generated by Django 4.2.6 on 2023-10-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок поста')),
                ('description', models.TextField(verbose_name='текст поста')),
                ('author', models.CharField(max_length=100, verbose_name='имя автора')),
                ('date', models.DateField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
