# Generated by Django 4.2.6 on 2023-10-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
